// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Api.Data;

#nullable disable

namespace Portfolio.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Portfolio.Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Portfolio.Api.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Portfolio.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiveUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Work Project",
                            Description = "BookIt is a full-featured booking management system built with ASP.NET Core Blazor. Businesses use it to manage appointments, resources, and customer bookings through a modern interface with light and dark mode support. Built on a clean architecture with real-time availability tracking, SMS notifications for customers, and a responsive MudBlazor UI.",
                            GitHubUrl = "https://github.com/dotnetappdev/bookit",
                            ImageUrl = "/images/bookit.svg",
                            IsFeatured = true,
                            ShortDescription = "A real-time Blazor booking management system",
                            Slug = "bookit",
                            SortOrder = 1,
                            TechStack = "Blazor, ASP.NET Core, SQL Server, Entity Framework Core, MudBlazor, C# .NET 10",
                            Title = "BookIt"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mobile Application",
                            Description = "A cross-platform mobile and desktop application built with .NET MAUI targeting iOS, Android, Windows, and macOS. Delivers a native experience across all platforms from a single shared codebase, with REST API integration and offline-friendly data handling.",
                            GitHubUrl = "https://github.com/dotnetappdev/maui-app",
                            ImageUrl = "/images/maui.png",
                            IsFeatured = true,
                            ShortDescription = "A .NET MAUI mobile and desktop application",
                            Slug = "maui-cross-platform-app",
                            SortOrder = 2,
                            TechStack = ".NET MAUI, C#, XAML, REST APIs",
                            Title = "MAUI Cross-Platform App"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Work Project",
                            Description = "Curo is a healthcare care management platform that replaced a paper-based system used by community carers. Built with Blazor and ASP.NET Core, it gives carers a task-driven workflow on any device and provides care managers with a live dashboard showing real-time visit progress. Hosted on Azure with full audit logging and role-based access control.",
                            GitHubUrl = "https://github.com/dotnetappdev/curo",
                            ImageUrl = "/images/curo.svg",
                            IsFeatured = true,
                            ShortDescription = "Healthcare care management platform",
                            Slug = "curo",
                            SortOrder = 3,
                            TechStack = "ASP.NET Core, Blazor, SQL Server, Entity Framework Core, Azure, MudBlazor, C# .NET 10",
                            Title = "Curo"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Healthcare",
                            Description = "A Patient CRM currently in development, designed to help healthcare providers manage patient relationships, appointments, communications, and care history in one centralised platform. Built with .NET 10, Blazor, and a REST API backend.",
                            GitHubUrl = "https://github.com/dotnetappdev/patient-crm",
                            ImageUrl = "/images/patient-crm.png",
                            IsFeatured = true,
                            ShortDescription = "Patient relationship management system (in development)",
                            Slug = "patient-crm",
                            SortOrder = 4,
                            TechStack = "ASP.NET Core .NET 10, Blazor, SQL Server, EF Core, REST API, MudBlazor",
                            Title = "Patient CRM"
                        },
                        new
                        {
                            Id = 5,
                            Category = "AI",
                            Description = "An AI assistant integrated into a healthcare platform that helps clinical staff surface relevant patient history, flag anomalies in test results, and draft care plan notes. Built on Semantic Kernel and Azure OpenAI with a strict evaluation layer that confidence-scores every response before it reaches clinical staff. All AI output is fully audited.",
                            GitHubUrl = "https://github.com/dotnetappdev/ai-diagnostic-assistant",
                            ImageUrl = "/images/ai-assistant.png",
                            IsFeatured = true,
                            ShortDescription = "AI-powered clinical decision support tool",
                            Slug = "ai-diagnostic-assistant",
                            SortOrder = 5,
                            TechStack = "Semantic Kernel, Azure OpenAI, ASP.NET Core, Blazor, SQL Server, Vector Search, .NET 10",
                            Title = "AI Diagnostic Assistant"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Security",
                            Description = "A reusable security baseline for ASP.NET Core APIs covering JWT authentication with algorithm pinning, OWASP Top Ten mitigations, rate limiting, structured security logging, and automated dependency vulnerability scanning in the CI pipeline. Used as the starting point for all new API projects so that security is built in from the first commit rather than retrofitted.",
                            GitHubUrl = "https://github.com/dotnetappdev/secure-api-framework",
                            ImageUrl = "/images/secure-api.png",
                            IsFeatured = true,
                            ShortDescription = "Hardened API security baseline for .NET",
                            Slug = "secure-api-framework",
                            SortOrder = 6,
                            TechStack = "ASP.NET Core, JWT, OAuth2, OWASP, Rate Limiting, Polly, GitHub Actions",
                            Title = "SecureAPI Framework"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Work Project",
                            Description = "TalentConnect is a full-featured recruitment management platform built with Blazor and ASP.NET Core. It streamlines the end-to-end hiring process with job posting management, a configurable multi-stage candidate pipeline, interview scheduling, automated notifications, and detailed recruitment analytics. Built for teams who want a data-driven hiring workflow without the spreadsheets.",
                            GitHubUrl = "https://github.com/dotnetappdev/talentconnect",
                            ImageUrl = "/images/talentconnect.svg",
                            IsFeatured = true,
                            ShortDescription = "A Blazor recruitment management platform",
                            Slug = "talentconnect",
                            SortOrder = 7,
                            TechStack = "Blazor, ASP.NET Core, SQL Server, Entity Framework Core, MudBlazor, REST API, C# .NET 10",
                            Title = "TalentConnect"
                        });
                });

            modelBuilder.Entity("Portfolio.Api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Languages",
                            Name = "C#",
                            Proficiency = 98
                        },
                        new
                        {
                            Id = 2,
                            Category = "Frameworks",
                            Name = "ASP.NET Core",
                            Proficiency = 95
                        },
                        new
                        {
                            Id = 3,
                            Category = "Frameworks",
                            Name = "Blazor",
                            Proficiency = 92
                        },
                        new
                        {
                            Id = 4,
                            Category = "Frameworks",
                            Name = ".NET MAUI",
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 5,
                            Category = "Databases",
                            Name = "SQL Server",
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 6,
                            Category = "Databases",
                            Name = "Entity Framework Core",
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 7,
                            Category = "Architecture",
                            Name = "REST API Design",
                            Proficiency = 92
                        },
                        new
                        {
                            Id = 8,
                            Category = "UI Frameworks",
                            Name = "MudBlazor",
                            Proficiency = 88
                        },
                        new
                        {
                            Id = 9,
                            Category = "Cloud",
                            Name = "Azure",
                            Proficiency = 82
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tools",
                            Name = "Git",
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 11,
                            Category = "Languages",
                            Name = "JavaScript",
                            Proficiency = 75
                        },
                        new
                        {
                            Id = 12,
                            Category = "Languages",
                            Name = "HTML/CSS",
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 13,
                            Category = "Frameworks",
                            Name = "WPF",
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 14,
                            Category = "Frameworks",
                            Name = "WinForms",
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 15,
                            Category = "Architecture",
                            Name = "Microservices",
                            Proficiency = 78
                        },
                        new
                        {
                            Id = 16,
                            Category = "AI",
                            Name = "Semantic Kernel",
                            Proficiency = 88
                        },
                        new
                        {
                            Id = 17,
                            Category = "AI",
                            Name = "Azure OpenAI",
                            Proficiency = 85
                        },
                        new
                        {
                            Id = 18,
                            Category = "AI",
                            Name = "ML.NET",
                            Proficiency = 75
                        },
                        new
                        {
                            Id = 19,
                            Category = "AI",
                            Name = "RAG Pipelines",
                            Proficiency = 82
                        },
                        new
                        {
                            Id = 20,
                            Category = "AI",
                            Name = "Vector Search",
                            Proficiency = 78
                        },
                        new
                        {
                            Id = 21,
                            Category = "Security",
                            Name = "OWASP Top Ten",
                            Proficiency = 90
                        },
                        new
                        {
                            Id = 22,
                            Category = "Security",
                            Name = "OAuth2 / OIDC",
                            Proficiency = 88
                        },
                        new
                        {
                            Id = 23,
                            Category = "Security",
                            Name = "JWT Authentication",
                            Proficiency = 92
                        },
                        new
                        {
                            Id = 24,
                            Category = "Security",
                            Name = "Threat Modelling",
                            Proficiency = 80
                        },
                        new
                        {
                            Id = 25,
                            Category = "Security",
                            Name = "Penetration Testing",
                            Proficiency = 72
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Portfolio.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Portfolio.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Portfolio.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
